### ISSUE TITLE
Compilation of saw_universal_robot fails under ros kinetic ubuntu 16.04

### ISSUE THREAD

**Issue by BrunoScaglioni** [jhu-cisst/cisst-saw#3]
Dear developers,
I am experiencing troubles in compiling cisst/saw in ROS kinetic, ubuntu 16.04. In particular, the build of "saw_universal_robot" fails with this error:

/home/bruno/catkin_ws/src/cisst-saw/sawUniversalRobot/components/code/mtsUniversalRobotScriptRT.cpp: In member function ‘void mtsUniversalRobotScriptRT::Init()’:
/home/bruno/catkin_ws/src/cisst-saw/sawUniversalRobot/components/code/mtsUniversalRobotScriptRT.cpp:189:21: error: ‘class mtsInterfaceProvided’ has no member named ‘AddMessageEvents’
         mInterface->AddMessageEvents();

Is Kinetic supported or should I swithc back to Indigo?
Attached you find the error dump
Many thanks, 
Bruno
[dump_fail.txt](https://github.com/jhu-cisst/cisst-saw/files/1280994/dump_fail.txt)

**Comment by pkazanzides** [comment]
This is probably not a ROS issue.  Are you building the master branch of 
cisst/saw?  My guess is that the master branch in sawUniversalRobot may 
be relying on features from the devel branch of cisst.  I will defer to 
Anton to confirm whether this is the case and provide a solution.

Peter

**Comment by BrunoScaglioni** [comment]
Yes, I am building the master branch of cisst/saw. 
Many thanks
Bruno

**Comment by simonleonard** [comment]
I've had the same problem for a while. But it compiles with the devel 
branch of CISST.

**Comment by adeguet1** [comment]
This has been fixed with cisst release 1.0.9
