### ISSUE TITLE
No CMakeLists.txt file in sawIntuitiveResearchKit/examples

### ISSUE THREAD

**Issue by linhongbin** [jhu-cisst/cisst-saw#4]
Hi there:

I get an error when using cmake configuring. It seems it is missing a CMakelist in sawIntuitiveResearchKit. 

CMake Error at sawIntuitiveResearchKit/CMakeLists.txt:16 (add_subdirectory):
  The source directory

    /home/ben/dvrk_ws/cisst-saw/sawIntuitiveResearchKit/examples

  does not contain a CMakeLists.txt file.

**Comment by adeguet1** [comment]
Fixed in master branch for sawIntuitiveResearchKit: https://github.com/jhu-dvrk/sawIntuitiveResearchKit/commit/83b1429cc88dd54897748b9854693e00fb9c364c

Also merged into devel branch.
